# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3838a385295f474c0219e3eab465ed58f5d20dc10a2672062f4ac5cc8f1580586cd896229aed7201540b7d0169a775b4a149dd0b7436387ddc3e71ca0e259cf

test:
  secret_key_base: 867093a59e69959a514813d47f3ca21ec1c441161d8ec93393af42488c17fc75c2272a248efd9ad97fc10838a7b5946dce5418aa0b912763e0a07976ca7b6929

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
